### ISSUE TITLE
Recomendação

### ISSUE THREAD

**Issue by audreyteles** [SamuelMTeixeira/SamuelMTeixeira#1]
Para deixar o README mais dinâmico recomendo o uso do WakaTime, ele te oferece várias informações sobre as linguagens de programação que você utiliza, repositórios e o tempo que você passa codando.

**Comment by SamuelMTeixeira** [comment]
Eu estava vendo um youtuber falando sobre e achei interessante, vou ver depois como funciona e implementarei em breve. Obg!
